name: Unit Tests
on:
  push:
    tags:
    - '*'
    branches:
    - main
    - release-*
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  workflow_call:
jobs:
  passAfailB:
    strategy:
      fail-fast: false
      matrix:
        var: [ 'A', 'B' ]
    runs-on: ubuntu-latest
    steps:
    - name: Check
      run: |
        [[ "${{ matrix.var }}" == "A" ]]
  next:
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: failure()
    needs:
    - passAfailB
    runs-on: ubuntu-latest
    steps:
    - name: What can we learn?
      run: |
        gh run view --jq '.' --json 'jobs' -R "${{ github.repository }}" "${{ github.run_id }}"
