name: Unit Tests
on:
    push:
        tags:
        - '*'
        branches:
        - main
        - release-*
    pull_request:
        types:
        - opened
        - reopened
        - synchronize
jobs:
    passAfailB:
        strategy:
            fail-fast: false
            matrix:
                var: [ 'A', 'B' ]
        runs-on: ubuntu-latest
        steps:
            - name: Check
              run: |
                [[ "${{ matrix.var }}" == "A" ]]

    next:
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure()
        needs:
            - passAfailB
        runs-on: ubuntu-latest
        steps:
            - name: What can we learn (failed jobs)?
              run: |
                # .jobs from this filtered to conclusion "failure" will give us name and url for the failing jobs
                gh run view --jq '.' --json 'jobs' -R "${{ github.repository }}" "${{ github.run_id }}" 

            - name: What can we learn (actor + commit)
              run: |
                echo '${{ toJson(github) }}'

            - name: Send custom JSON data to Slack workflow
              uses: slackapi/slack-github-action@v1.24.0
              with:
                # For posting a rich message using Block Kit
                payload: |
                    {
                        "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                        "blocks": [
                        {
                            "type": "section",
                            "text": {
                            "type": "mrkdwn",
                            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                            }
                        }
                        ]
                    }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_INTEGRATION_TEST_WEBHOOK }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK