name: Unit Tests
on:
    push:
        tags:
        - '*'
        branches:
        - main
        - release-*
    pull_request:
        types:
        - opened
        - reopened
        - synchronize
jobs:
    passAfailB:
        strategy:
            fail-fast: false
            matrix:
                var: [ 'A', 'B' ]
        runs-on: ubuntu-latest
        steps:
            - name: Check
              run: |
                [[ "${{ matrix.var }}" == "A" ]]

    anotherFail:
        runs-on: ubuntu-latest
        steps:
            - run: false

    slack-on-failure:
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SLACK_CI_INTEGRATION_TESTING_WEBHOOK: ${{ secrets.SLACK_CI_INTEGRATION_TEST_WEBHOOK }}
            TEST_FAILURES_NOTIFY_WEBHOOK: ${{ secrets.SLACK_CI_INTEGRATION_TEST_WEBHOOK }}
        if: |
            failure() && (
                github.event_name == 'push' || 
                contains(github.event.pull_request.labels.*.name, 'ci-test-github-action-slack-messages')
            )
        needs:
            - passAfailB
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: stackrox/stackrox
            ref: gavin/99pc/slack-workflow-failure
          
        - name: Slack message
          run: |
            source scripts/ci/lib.sh
            slack_workflow_failure '${{ toJson(github) }}'
